export const BASE_URL: string = process.env.NEXT_PUBLIC_BACKEND_URL;

export const FLAGGED_ACTIONS_SCORE = {
    MULTIPLE_FACES_IN_CAMERA: 10,
    FACE_NOT_DETECTED: 10,
    WINDOW_FOCUS_CHANGE: 20,
    EXIT_FULLSCREEN: 10,
    NOT_LOOKING_IN_CAMERA: 5
}